- name: Import Docker Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: docker-ce-install

- name: Start App container
  community.docker.docker_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
    ports:
     - "8080:8080"
    env:
      MONGO: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/user:MONGO token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}"
      MONGO_URL: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/user:MONGO_URL token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}"
      REDIS_URL: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/user:REDIS_URL token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}"


