- name: Copy RabbitMQ repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install RabbitMQ
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: Add Application User
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/rabbitmq:AMQP_USER token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}"
    password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/rabbitmq:AMQP_PASS token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present




