- name: Import Docker Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: docker-ce-install

- name: Start App container
  community.docker.docker_container:
    name: shipping
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
    ports:
     - "8080:8080"
    env:
      CART_ENDPOINT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/shipping:CART_ENDPOINT token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}"
      DB_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/shipping:DB_HOST token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}"


- name: Schema container
  loop:
    - app-user
    - schema
    - master-data
  community.docker.docker_container:
    name: shipping-schema-{{item}}
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    env:
      DB_TYPE: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/catalogue:DB_TYPE token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}"
      APP_GIT_URL: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/catalogue:APP_GIT_URL token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}"
      DB_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/catalogue:DB_HOST token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}"
      SCHEMA_FILE: "db/{{ item }}.sql"



