- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Set MySQL Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/mysql:MYSQL_ROOT_PASSWORD token={{ vault_token }} url=http://vault-internal.azdevopsb82.online:8200') }}

- name: Install prometheus node exporter
  ansible.builtin.include_role:
    name: common
    tasks_from: prometheus-node-exporter


